##    makeCacheMatrix() and cacheSolve()

##    makeCacheMatrix() and cacheSolve() used together provide a way
##    to avoid repeated calculations of the inverse of a matrix. 
##    The matrix is first stored in a special "matrix" object created
##    by makeCacheMatrix(). Calling cacheSolve() with that special object
##    as the parameter returns the matrix inverse, invoking solve() only 
##    when a cached value is not available. The user of cacheSolve() 
##    need not keep track of caching even if the matrix value stored in
##    the special object were to be reset with the object's set() method.

## ````````````````````````````````````````````````````````````````````````
## makeCacheMatrix creates a special "matrix" object that can cache its
##      inverse. Four methods defined inside of makeCacheMatrix have
##      access to the matrix (x) and its inverse (xI) from the
##      makeCacheMatrix environment:
##
##        set(y) - sets the cached matrix to a new value and NULLs out
##                 any previously cached inverse
##
##        get() - returns the currently cached matrix
##
##        setinverse(inverse) - sets a new value for the cached inverse
##                              (Note caller of setinverse() is responsible
##                              for providing the correct value.)
##
##        getinverse() - returns the currently cached inverse
##
## makeCacheMatrix returns a named list containing the 4 methods.

makeCacheMatrix <- function(x = matrix()) {
        xI <- NULL
        
        set <- function(y) {
                x <<- y
                xI <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) xI <<- inverse
        getinverse <- function() xI
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}

## ````````````````````````````````````````````````````````````````````````
## cacheSolve computes the inverse of a special "matrix" returned
##      by makeCacheMatrix above. If the inverse has already been
##      calculated (and the matrix has not changed), then cachesolve
##      retrieves the inverse from the cache. But if no previously 
##      calculated inverse is available then cachesolve calculates
##      the inverse and caches that result.
##
##      sMatrix - a special matrix created by makeCacheMatrix
##      x - matrix itself
##      xI - inverse of x
##
## cacheSolve returns the inverse of a matrix stored in a special
##      "matrix" that was generated by makeCacheMatrix

cacheSolve <- function(sMatrix, ...) {
        xI <- sMatrix$getinverse()
        if(!is.null(xI)) {
                message("getting cached data")
                return(xI)
        }
        x <- sMatrix$get()
        xI <- solve(x, ...)
        sMatrix$setinverse(xI)
        xI
}
